create table if not exists public.fmp_subscriptions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  email text,
  plan text not null check (plan in ('monthly','yearly')),
  razorpay_subscription_id text unique not null,
  status text not null default 'created',
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists fmp_subscriptions_user_id_idx on public.fmp_subscriptions(user_id);
